spring:
  cloud:
    gateway:
      routes:
      - id: convertcurrencyms
        uri: lb://convertcurrencyms
        predicates:
        - Path=/convertcurrency/**
      - id: currencyconfactms
        uri: lb://currencyconfactms
        predicates:
        - Path=/confact/**
      - id: accountlogin
        uri: lb://accountlogin
        predicates:
        - Path=/account/**