spring:
  cloud:
    gateway:
      routes:
      - id: convertcurrencyms
        uri: lb://convertcurrencyms
        predicates:
        - Path=/convertcurrency/**
      - id: currencyconfactms
        uri: lb://currencyconfactms
        predicates:
        - Path=/confact/**
      - id: accountlogin
        uri: lb://accountlogin
        predicates:
        - Path=/account/**
      - id: productms
        uri: lb://productms
        predicates:
        - Path=/product/**
      - id: cartms
        uri: lb://cartms
        predicates:
        - Path=/cart/**
      - id: orderms
        uri: lb://orderms
        predicates:
        - Path=/order/**